/** Catálogo editorial. Cada alternativa conserva su documentación primaria. */
export type Library = { id: string; name: string; purpose: string; choose: string; limit: string; hardware: string; docs: string };
const lib = (id: string, name: string, purpose: string, choose: string, limit: string, hardware: string, docs: string): Library => ({ id, name, purpose, choose, limit, hardware, docs });
export const libraries: Library[] = [
  lib('numpy', 'NumPy', 'Arrays, álgebra lineal y simulación numérica.', 'Cálculo vectorizado y datos numéricos en memoria.', 'Vigila copias, precisión y tamaño de los arrays.', 'CPU', 'https://numpy.org/doc/stable/'),
  lib('scipy', 'SciPy', 'Estadística, señales y optimización numérica.', 'Necesitas métodos científicos sobre arrays de NumPy.', 'El método elegido depende de los supuestos del problema.', 'CPU', 'https://docs.scipy.org/doc/scipy/'),
  lib('pandas', 'pandas', 'Lectura, limpieza y análisis de tablas.', 'EDA iterativo y compatibilidad con el ecosistema Python.', 'El volumen de datos debe encajar en la memoria disponible.', 'CPU', 'https://pandas.pydata.org/docs/user_guide/'),
  lib('polars', 'Polars', 'Transformaciones de tablas con ejecución lazy y streaming.', 'ETL por expresiones y consultas que puedes optimizar.', 'Algunas operaciones requieren materializar datos en memoria.', 'CPU · paralelismo', 'https://docs.pola.rs/user-guide/'),
  lib('pandera', 'Pandera', 'Validación de esquemas y valores en DataFrames.', 'Contratos de datos con tipos, rangos y reglas verificables.', 'Debes definir reglas relevantes para tu dominio.', 'CPU', 'https://pandera.readthedocs.io/en/stable/'),
  lib('pydantic', 'Pydantic', 'Validación de objetos y configuración tipada.', 'Entradas de una API y configuración de experimentos.', 'No sustituye el análisis de calidad de un dataset.', 'CPU', 'https://docs.pydantic.dev/latest/'),
  lib('matplotlib', 'Matplotlib', 'Figuras científicas y gráficos estáticos.', 'Control fino y exportación de figuras para informes o papers.', 'La interacción avanzada necesita trabajo adicional.', 'CPU', 'https://matplotlib.org/stable/'),
  lib('plotly', 'Plotly', 'Gráficos interactivos y exploración visual.', 'Necesitas zoom, tooltips y gráficos compartibles en HTML.', 'Grandes cantidades de puntos pueden ralentizar el navegador.', 'CPU · navegador', 'https://plotly.com/python/'),
  lib('statsmodels', 'statsmodels', 'Modelos estadísticos, contrastes y diagnósticos.', 'Interpretar coeficientes, residuos e intervalos con supuestos explícitos.', 'Comprueba independencia, distribución y especificación del modelo.', 'CPU', 'https://www.statsmodels.org/stable/index.html'),
  lib('sklearn', 'scikit-learn', 'Preprocesamiento, ML clásico, particiones y métricas.', 'Baselines reproducibles con Pipeline y validación adecuada.', 'No es un framework de entrenamiento de redes profundas.', 'CPU', 'https://scikit-learn.org/stable/user_guide.html'),
  lib('catboost', 'CatBoost', 'Boosting para clasificación, regresión y ranking.', 'Tablas con variables categóricas y un baseline potente.', 'Controla sobreajuste y evalúa con grupos o tiempo si corresponde.', 'CPU / GPU', 'https://catboost.ai/docs/'),
  lib('xgboost', 'XGBoost', 'Árboles de boosting con objetivos configurables.', 'Tabular con control de regularización y restricciones.', 'El ajuste y la codificación de categorías siguen importando.', 'CPU / GPU', 'https://xgboost.readthedocs.io/en/stable/'),
  lib('lightgbm', 'LightGBM', 'Boosting por histogramas para tablas.', 'Dataset grande y presupuesto ajustado de entrenamiento.', 'Ajusta complejidad de hojas para evitar sobreajuste.', 'CPU / GPU', 'https://lightgbm.readthedocs.io/en/stable/'),
  lib('shap', 'SHAP', 'Atribuciones locales y globales de predicciones.', 'Explicar cómo un modelo utiliza las variables.', 'Las atribuciones no demuestran causalidad; vigila correlaciones.', 'CPU / según modelo', 'https://shap.readthedocs.io/en/latest/'),
  lib('opencv', 'OpenCV', 'Imagen, vídeo, geometría y calibración de cámaras.', 'Pipeline clásico, cámara en tiempo real o pose geométrica.', 'Cuida convenciones, distorsión y sistemas de coordenadas.', 'CPU · GPU según build', 'https://docs.opencv.org/4.x/d6/d00/tutorial_py_root.html'),
  lib('skimage', 'scikit-image', 'Filtros, morfología, medidas y segmentación clásica.', 'Análisis científico de imágenes y prototipos legibles.', 'No proporciona un catálogo general de modelos profundos.', 'CPU', 'https://scikit-image.org/docs/stable/'),
  lib('ultralytics', 'Ultralytics', 'Detección, segmentación, pose y tracking con la familia YOLO.', 'Entrenar y exportar rápidamente un detector; compara YOLO26 y modelos previos en tu equipo.', 'Valida latencia y precisión en el hardware final; revisa licencia de uso.', 'CPU / GPU · edge', 'https://docs.ultralytics.com/models/'),
  lib('torchvision', 'Torchvision', 'Datasets, transformaciones y modelos de visión para PyTorch.', 'Clasificación o detección con componentes que puedas modificar.', 'Entrenamiento y despliegue requieren configurar el pipeline.', 'CPU / GPU', 'https://docs.pytorch.org/vision/stable/'),
  lib('sam2', 'SAM 2', 'Segmentación guiada por prompts en imágenes y vídeo.', 'Generar máscaras, asistir anotación o seguir un objeto señalado.', 'No asigna automáticamente las clases de tu dominio.', 'GPU recomendada', 'https://github.com/facebookresearch/sam2'),
  lib('depth', 'Depth Anything V2', 'Estimación de profundidad monocular con modelos relativos y métricos.', 'Baseline de profundidad; usa un checkpoint métrico si necesitas distancia.', 'La salida relativa no da metros; valida escala y dominio.', 'GPU recomendada', 'https://github.com/DepthAnything/Depth-Anything-V2'),
  lib('open3d', 'Open3D', 'Nubes de puntos, registro y reconstrucción 3D.', 'Procesar RGB-D, alinear nubes y evaluar geometría 3D.', 'La geometría hereda errores de calibración y profundidad.', 'CPU / GPU según módulo', 'https://www.open3d.org/docs/release/'),
  lib('pytorch', 'PyTorch', 'Autograd, tensores y entrenamiento de redes neuronales.', 'Arquitecturas y pérdidas propias en proyectos de investigación.', 'La flexibilidad exige mantener entrenamiento y evaluación.', 'CPU / GPU', 'https://docs.pytorch.org/docs/stable/'),
  lib('keras', 'Keras', 'API de alto nivel para redes neuronales con varios backends.', 'Prototipos de DL con entrenamiento y capas estandarizados.', 'La portabilidad depende de las operaciones y del backend.', 'CPU / GPU', 'https://keras.io/guides/'),
  lib('lightning', 'Lightning', 'Organización del entrenamiento y ejecución distribuida en PyTorch.', 'Quieres reducir código repetitivo y escalar experimentos.', 'Añade una abstracción que debes entender al depurar.', 'CPU / GPU · multi-GPU', 'https://lightning.ai/docs/pytorch/stable/'),
  lib('timm', 'timm', 'Modelos preentrenados y recetas de clasificación visual.', 'Backbones de referencia y transfer learning para imágenes.', 'Revisa preprocesamiento y licencia de cada checkpoint.', 'CPU / GPU', 'https://huggingface.co/docs/timm/index'),
  lib('kornia', 'Kornia', 'Geometría y transformaciones diferenciables de visión.', 'Procesamiento integrado en un grafo PyTorch o sobre GPU.', 'Exige cuidar formas de tensores y convenciones geométricas.', 'CPU / GPU', 'https://kornia.readthedocs.io/en/latest/'),
  lib('sktime', 'sktime', 'Interfaces para forecasting y aprendizaje con series.', 'Comparar modelos temporales con pipelines y backtesting.', 'Configura ventanas y horizonte sin información futura.', 'CPU / según estimador', 'https://www.sktime.net/en/stable/'),
  lib('statsforecast', 'StatsForecast', 'Modelos estadísticos para forecasting de muchas series.', 'Baselines de demanda o sensores con ARIMA y ETS.', 'Covariables y cambios de régimen requieren diseño específico.', 'CPU · paralelismo', 'https://nixtlaverse.nixtla.io/statsforecast/'),
  lib('tsfresh', 'tsfresh', 'Extracción y selección de features de series temporales.', 'Convertir ventanas de sensores en variables para ML tabular.', 'Muchas features implican coste y riesgo de fuga entre ventanas.', 'CPU · paralelismo', 'https://tsfresh.readthedocs.io/en/latest/'),
  lib('river', 'River', 'ML incremental y aprendizaje sobre flujos de datos.', 'Actualización muestra a muestra y evaluación prequential.', 'Necesitas etiquetas y política de actualización bien definidas.', 'CPU', 'https://riverml.xyz/latest/'),
  lib('optuna', 'Optuna', 'Búsqueda de hiperparámetros y poda de ensayos.', 'Optimizar un objetivo medible bajo presupuesto de cómputo.', 'La búsqueda no debe utilizar el test final.', 'CPU / según ensayo', 'https://optuna.readthedocs.io/en/stable/'),
  lib('cvxpy', 'CVXPY', 'Modelado declarativo de optimización convexa.', 'El problema admite una formulación convexa verificable.', 'Necesitas un solver compatible y una formulación válida.', 'CPU · solver', 'https://www.cvxpy.org/'),
  lib('pyomo', 'Pyomo', 'Modelado algebraico de optimización con restricciones.', 'Planificación industrial, energía y problemas mixtos.', 'El solver se instala aparte; el coste depende de la formulación.', 'CPU · solver externo', 'https://pyomo.readthedocs.io/en/stable/'),
  lib('ortools', 'OR-Tools', 'Optimización combinatoria, scheduling y rutas.', 'Asignación, turnos y restricciones discretas con CP-SAT.', 'CP-SAT requiere expresar variables y restricciones enteras.', 'CPU', 'https://developers.google.com/optimization'),
  lib('transformers', 'Transformers', 'Modelos preentrenados para texto, audio y visión.', 'Inferencia o adaptación de un modelo abierto a tu tarea.', 'Memoria, licencia y calidad dependen del modelo concreto.', 'CPU / GPU', 'https://huggingface.co/docs/transformers/index'),
  lib('peft', 'PEFT', 'Adaptación eficiente de modelos con métodos como LoRA.', 'Fine-tuning cuando entrenar todos los pesos es costoso.', 'Ahorra parámetros entrenables; no elimina memoria del modelo base.', 'GPU recomendada', 'https://huggingface.co/docs/peft/index'),
  lib('sentence', 'Sentence Transformers', 'Embeddings y reranking para texto.', 'Búsqueda semántica, similitud y recuperación en RAG.', 'Evalúa idioma y dominio con consultas representativas.', 'CPU / GPU', 'https://www.sbert.net/'),
  lib('faiss', 'FAISS', 'Índices para búsqueda de vectores por similitud.', 'Recuperación local de embeddings a escala.', 'El índice no gestiona por sí solo permisos ni documentos.', 'CPU / GPU', 'https://faiss.ai/'),
  lib('diffusers', 'Diffusers', 'Pipelines y modelos de difusión generativa.', 'Síntesis o edición de imágenes con modelos disponibles.', 'Generar datos no garantiza mejorar la generalización.', 'GPU recomendada', 'https://huggingface.co/docs/diffusers/index'),
  lib('vllm', 'vLLM', 'Serving de LLM con batching y gestión de memoria.', 'Servicio con varias peticiones y GPU compatible.', 'Comprueba soporte de modelo, hardware y memoria disponible.', 'GPU habitual', 'https://docs.vllm.ai/en/latest/'),
  lib('llamacpp', 'llama-cpp-python', 'Interfaz Python de llama.cpp para inferencia local.', 'LLM en GGUF cuantizado con CPU o aceleración local.', 'Throughput y calidad dependen de cuantización y hardware.', 'CPU / GPU según build', 'https://llama-cpp-python.readthedocs.io/en/latest/'),
  lib('onnx', 'ONNX Runtime', 'Inferencia de modelos ONNX con distintos proveedores.', 'Portabilidad CPU/GPU y separación entre training y serving.', 'Verifica operadores, formas y paridad tras exportar.', 'CPU / GPU · según proveedor', 'https://onnxruntime.ai/docs/'),
  lib('tensorrt', 'TensorRT', 'Optimización e inferencia en GPU NVIDIA.', 'Latencia en Jetson o GPU NVIDIA tras medir una referencia.', 'Comprueba compatibilidad de JetPack/CUDA y precisión de cuantización.', 'NVIDIA GPU · Jetson', 'https://docs.nvidia.com/deeplearning/tensorrt/latest/'),
  lib('openvino', 'OpenVINO', 'Optimización e inferencia sobre hardware compatible de Intel.', 'CPU Intel o aceleradores Intel con un modelo soportado.', 'Comprueba dispositivos y operadores antes de migrar.', 'Intel CPU / GPU / NPU', 'https://docs.openvino.ai/'),
  lib('fastapi', 'FastAPI', 'API Python con validación y documentación automática.', 'Integrar inferencia en un servicio HTTP tipado.', 'Debes gestionar carga, procesos y ciclo de vida del modelo.', 'CPU / backend del modelo', 'https://fastapi.tiangolo.com/'),
  lib('bentoml', 'BentoML', 'Empaquetado y serving de modelos de ML.', 'Servicios de inferencia con empaquetado específico de modelos.', 'Añade un framework operativo que debes mantener.', 'CPU / GPU', 'https://docs.bentoml.com/en/latest/'),
  lib('mlflow', 'MLflow', 'Registro de experimentos, artefactos y modelos.', 'Trazabilidad de parámetros, métricas y versiones de modelos.', 'Configura almacenamiento y acceso del tracking server.', 'CPU · servicio', 'https://mlflow.org/docs/latest/'),
  lib('dvc', 'DVC', 'Versionado de datos y pipelines junto a Git.', 'Reproducir datasets y etapas sin meter binarios en Git.', 'Los datos se guardan en un remoto que debes configurar.', 'CPU · almacenamiento', 'https://dvc.org/doc'),
  lib('evidently', 'Evidently', 'Evaluación de calidad, drift y sistemas de IA.', 'Comparar referencia y producción con métricas monitorizadas.', 'Drift no implica automáticamente una pérdida de precisión.', 'CPU', 'https://docs.evidentlyai.com/'),
];

export const categories = [
  { id: 'fundamentos', name: 'Fundamentos transversales', short: 'Fundamentos', description: 'Datos fiables, análisis y experimentos bien planteados.' },
  { id: 'tabular', name: 'Datos tabulares y ML clásico', short: 'Tabular y ML clásico', description: 'Baselines sólidos antes de añadir complejidad.' },
  { id: 'vision', name: 'Visión', short: 'Visión', description: 'De píxeles y cámaras a detección y geometría 3D.' },
  { id: 'deep', name: 'Deep learning', short: 'Deep learning', description: 'Entrenamiento, modelos de referencia y adaptación.' },
  { id: 'series', name: 'Series temporales', short: 'Series temporales', description: 'Sensores, señales y predicción respetando el tiempo.' },
  { id: 'optimizacion', name: 'Optimización', short: 'Optimización', description: 'Decisiones y búsqueda bajo objetivos y restricciones.' },
  { id: 'generativa', name: 'IA generativa', short: 'IA generativa', description: 'Modelos de lenguaje, recuperación y generación.' },
  { id: 'despliegue', name: 'Despliegue', short: 'Despliegue', description: 'Inferencia medida en el hardware y sistema finales.' },
  { id: 'mlops', name: 'MLOps', short: 'MLOps', description: 'Trazabilidad, reproducción y seguimiento en producción.' },
];
export const problems = ['Análisis de datos', 'Clasificación', 'Regresión', 'Clustering', 'Anomalías', 'Detección', 'Segmentación', 'Geometría 3D', 'Forecasting', 'Señales y sensores', 'Optimización', 'Texto y RAG', 'Generación', 'Infraestructura'];
export const phases = ['Datos', 'Exploración', 'Modelado', 'Entrenamiento', 'Evaluación', 'Despliegue', 'Monitorización'];
export type Capability = { id: string; category: string; title: string; description: string; problems: string[]; phases: string[]; libs: string[]; tip: string };
const cap = (id: string, category: string, title: string, description: string, problems: string[], phases: string[], libs: string[], tip: string): Capability => ({id, category, title, description, problems, phases, libs, tip});
export const capabilities: Capability[] = [
  cap('numerico','fundamentos','Cálculo científico','Arrays, simulación y operaciones numéricas.',['Análisis de datos','Optimización'],['Datos','Modelado'],['numpy','scipy'],'Empieza por vectorizar y medir; evita optimizar sin un perfil de ejecución.'),
  cap('tablas','fundamentos','Lectura y transformación de datos','Limpiar, unir y agregar tablas con un flujo reproducible.',['Análisis de datos'],['Datos','Exploración'],['pandas','polars'],'pandas para explorar; considera Polars cuando el ETL y el volumen sean el cuello de botella.'),
  cap('calidad','fundamentos','Contratos y calidad de datos','Detectar errores de tipos, rangos y entradas.',['Análisis de datos','Infraestructura'],['Datos','Evaluación','Monitorización'],['pandera','pydantic'],'Define el contrato de entrada antes de entrenar y compruébalo al recibir datos nuevos.'),
  cap('visualizar','fundamentos','EDA y visualización','Examinar distribuciones, relaciones y resultados.',['Análisis de datos'],['Exploración','Evaluación'],['matplotlib','plotly'],'Usa figuras estáticas para publicar e interacción para investigar casos y rangos.'),
  cap('estadistica','fundamentos','Estadística e incertidumbre','Contrastes, intervalos y diagnósticos de supuestos.',['Análisis de datos','Regresión'],['Exploración','Evaluación'],['statsmodels','scipy'],'Reporta tamaño del efecto e incertidumbre; adapta el remuestreo a grupos o dependencia temporal.'),
  cap('validacion','fundamentos','Particiones y métricas','Diseñar una evaluación que represente el uso real.',['Clasificación','Regresión','Anomalías'],['Modelado','Evaluación'],['sklearn'],'Separa por persona, máquina o tiempo cuando haya dependencia. Reserva el test final.'),
  cap('preprocesado','tabular','Preprocesamiento y selección','Imputación, escalado, encoding y selección de variables.',['Clasificación','Regresión'],['Datos','Modelado'],['sklearn'],'Ajusta transformaciones dentro de cada fold mediante Pipeline para evitar fuga de información.'),
  cap('baseline','tabular','Clasificación y regresión','Modelos lineales, vecinos, SVM y árboles de referencia.',['Clasificación','Regresión'],['Modelado','Entrenamiento','Evaluación'],['sklearn','catboost'],'Empieza con un baseline simple, una métrica de negocio y una partición válida.'),
  cap('boosting','tabular','Boosting para datos tabulares','Comparar ensembles de árboles para predicción.',['Clasificación','Regresión'],['Modelado','Entrenamiento'],['catboost','xgboost','lightgbm'],'Compara las tres alternativas con la misma partición y presupuesto, sin asumir un ganador universal.'),
  cap('no-supervisado','tabular','Clustering y anomalías','Agrupar, reducir dimensión y detectar casos atípicos.',['Clustering','Anomalías'],['Exploración','Modelado','Evaluación'],['sklearn','river'],'Valida clusters y umbrales con conocimiento del dominio; una proyección bonita no valida un modelo.'),
  cap('interpretar','tabular','Interpretabilidad','Entender variables y predicciones individuales.',['Clasificación','Regresión'],['Evaluación','Monitorización'],['shap','sklearn'],'Combina atribuciones con permutation importance y análisis de errores por subgrupo.'),
  cap('vision-clasica','vision','Visión clásica y cámaras','Filtros, morfología, features, calibración y pose.',['Segmentación','Geometría 3D','Análisis de datos'],['Datos','Exploración','Modelado'],['opencv','skimage'],'Prueba un método clásico si el entorno es controlado; calibra antes de estimar medidas.'),
  cap('deteccion','vision','Detección y tracking','Localizar objetos y asociarlos a lo largo del vídeo.',['Detección'],['Modelado','Entrenamiento','Evaluación','Despliegue'],['ultralytics','torchvision'],'Mide precisión por clase y latencia extremo a extremo; el tracking depende también de asociación y cámara.'),
  cap('segmentacion','vision','Segmentación de imágenes y vídeo','Obtener máscaras para inspección, anotación o seguimiento.',['Segmentación'],['Datos','Modelado','Evaluación'],['sam2','ultralytics','skimage'],'SAM 2 sirve para prompts y anotación; para clases específicas valora segmentación supervisada.'),
  cap('profundidad','vision','Profundidad monocular','Estimar profundidad relativa o métrica desde una imagen.',['Geometría 3D'],['Modelado','Evaluación','Despliegue'],['depth'],'No conviertas profundidad relativa en metros sin calibración. Evalúa escala en escenas no vistas.'),
  cap('geometria','vision','Geometría y localización 3D','Reconstrucción, registro de nubes y proyección de cámara.',['Geometría 3D'],['Datos','Modelado','Evaluación'],['open3d','opencv'],'Documenta intrínsecos, extrínsecos, unidades y transformaciones entre marcos de referencia.'),
  cap('entrenar-red','deep','Entrenar redes neuronales','Construir arquitecturas, pérdidas y bucles de entrenamiento.',['Clasificación','Regresión','Detección','Generación'],['Modelado','Entrenamiento'],['pytorch','keras','lightning'],'PyTorch para control fino; Keras para una API alta; Lightning para organizar entrenamiento PyTorch.'),
  cap('transfer','deep','Modelos de referencia y transfer learning','Reutilizar backbones y adaptar pesos preentrenados.',['Clasificación','Detección'],['Modelado','Entrenamiento','Evaluación'],['timm','torchvision'],'Comprueba preprocesamiento y compara freezing y fine-tuning con una referencia entrenada igual.'),
  cap('aumentar','deep','Transformaciones y augmentación','Introducir variaciones compatibles con el problema.',['Clasificación','Detección','Segmentación'],['Datos','Entrenamiento'],['torchvision','kornia'],'Transforma imagen y etiquetas de forma consistente; reserva la evaluación para datos sin augmentación aleatoria.'),
  cap('signal','series','Procesamiento de señales','Filtrar, analizar frecuencias y detectar eventos en sensores.',['Señales y sensores','Anomalías'],['Datos','Exploración'],['scipy','numpy'],'Respeta frecuencia de muestreo y aliasing; un filtro no causal puede invalidar una prueba online.'),
  cap('forecast','series','Predicción temporal','Baselines estadísticos y comparación con backtesting.',['Forecasting','Regresión'],['Modelado','Entrenamiento','Evaluación'],['statsforecast','sktime','statsmodels'],'Evalúa con ventanas temporales y el horizonte de uso; compara contra una predicción naive.'),
  cap('features-series','series','Features de sensores','Convertir ventanas de series en datos para modelos tabulares.',['Señales y sensores','Clasificación','Anomalías'],['Datos','Modelado'],['tsfresh','scipy'],'Separa máquinas o sesiones antes de generar ventanas para evitar que train y test se solapen.'),
  cap('online','series','Aprendizaje en streaming','Actualizar modelos y evaluar sobre flujos de muestras.',['Anomalías','Clasificación','Regresión'],['Modelado','Monitorización'],['river'],'Predice antes de aprender cada muestra y contempla el retraso de llegada de las etiquetas.'),
  cap('hparams','optimizacion','Búsqueda de hiperparámetros','Seleccionar configuraciones con un presupuesto definido.',['Optimización'],['Entrenamiento','Evaluación'],['optuna','sklearn'],'Guarda semilla, objetivo y presupuesto; utiliza validación para buscar y test para la comparación final.'),
  cap('convexa','optimizacion','Optimización continua y convexa','Ajustar parámetros o decisiones bajo restricciones.',['Optimización'],['Modelado'],['cvxpy','scipy'],'CVXPY para formulación convexa; SciPy para métodos numéricos generales y ajuste local.'),
  cap('industrial','optimizacion','Planificación y optimización industrial','Asignación, rutas, turnos y modelos algebraicos.',['Optimización'],['Modelado','Evaluación'],['pyomo','ortools'],'Pyomo si necesitas expresar un modelo algebraico y elegir solver; OR-Tools para problemas discretos y scheduling.'),
  cap('llm','generativa','Modelos de lenguaje y adaptación','Inferencia y fine-tuning de modelos preentrenados.',['Texto y RAG','Generación'],['Modelado','Entrenamiento','Evaluación'],['transformers','peft'],'Elige un modelo con una evaluación del dominio. PEFT complementa Transformers para adaptación eficiente.'),
  cap('rag','generativa','Embeddings y recuperación para RAG','Representar texto y recuperar contenido relevante.',['Texto y RAG'],['Datos','Modelado','Evaluación'],['sentence','faiss'],'Estas herramientas se complementan: embeddings y reranking frente a índice vectorial. Evalúa recuperación y respuesta por separado.'),
  cap('difusion','generativa','Generación de imágenes','Crear o editar imágenes con modelos de difusión.',['Generación'],['Datos','Modelado','Evaluación'],['diffusers'],'Si generas datos sintéticos, mide su efecto en un test real independiente.'),
  cap('servir-llm','generativa','Inferencia local y serving de LLM','Ejecutar modelos de lenguaje con recursos controlados.',['Texto y RAG','Generación'],['Despliegue'],['vllm','llamacpp'],'vLLM para throughput de servicio; llama-cpp-python para ejecución local con GGUF y cuantización.'),
  cap('inferencia','despliegue','Inferencia portable','Ejecutar modelos fuera del entorno de entrenamiento.',['Infraestructura','Clasificación','Detección'],['Evaluación','Despliegue'],['onnx','openvino'],'Verifica paridad numérica, shapes dinámicos y latencia con entradas representativas.'),
  cap('edge','despliegue','Aceleración en NVIDIA y edge','Optimizar inferencia para Jetson y GPU NVIDIA.',['Infraestructura','Detección','Segmentación','Geometría 3D'],['Evaluación','Despliegue'],['tensorrt','onnx'],'Mide p50/p95, memoria y potencia en el dispositivo final. Cuantizar exige volver a evaluar precisión.'),
  cap('api','despliegue','Servicios de inferencia','Exponer modelos mediante APIs integrables.',['Infraestructura'],['Despliegue'],['fastapi','bentoml'],'Define esquema, tiempo máximo, concurrencia y carga del modelo antes de integrar el cliente.'),
  cap('experimentos','mlops','Experimentos y artefactos','Registrar parámetros, métricas y modelos para compararlos.',['Infraestructura'],['Entrenamiento','Evaluación','Despliegue'],['mlflow'],'Relaciona cada resultado con código, datos, configuración y artefacto del modelo.'),
  cap('versionar','mlops','Versionado de datos y pipelines','Reproducir datasets y etapas del proyecto.',['Infraestructura','Análisis de datos'],['Datos','Entrenamiento'],['dvc','mlflow'],'DVC versiona datos y etapas; MLflow registra ejecuciones y modelos. Úsalos juntos si necesitas ambas funciones.'),
  cap('drift','mlops','Monitorización y drift','Comprobar cambios de datos y calidad tras desplegar.',['Infraestructura','Anomalías'],['Evaluación','Monitorización'],['evidently','river'],'Define referencia, ventanas y umbrales. Cuando haya etiquetas, mide también rendimiento real.'),
];

export const normalize = (text: string) => text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
export type Filters = { query: string; category: string; problem: string; phase: string };
/** Filtros combinados con AND; búsqueda por palabras en capacidad y alternativas. */
export function filterCapabilities(filters: Filters) {
  const terms = normalize(filters.query).trim().split(/\s+/).filter(Boolean);
  return capabilities.filter(c => {
    const haystack = normalize([c.title,c.description,c.tip,...c.problems,...c.phases,...c.libs.map(id=>{const l=libraries.find(x=>x.id===id)!;return l.name+' '+l.purpose+' '+l.choose;})].join(' '));
    return (!filters.category || c.category===filters.category) && (!filters.problem || c.problems.includes(filters.problem)) && (!filters.phase || c.phases.includes(filters.phase)) && terms.every(t=>haystack.includes(t));
  });
}
/** Comparación explícita, sin duplicados, limitada a tres alternativas. */
export function toggleSelection(selected: string[], id: string) {
  if (!libraries.some(l=>l.id===id)) throw new Error('Librería desconocida');
  if (selected.includes(id)) return selected.filter(x=>x!==id);
  if (selected.length>=3) throw new Error('Puedes comparar hasta 3 librerías. Quita una para añadir otra.');
  return [...selected,id];
}
